services:
  - type: web
    name: ncufoodmap
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: cd NCUFOODMAP_DJANGO || cd foodmap/NCUFOODMAP_DJANGO && gunicorn ncufoodmap_backend.wsgi:application --log-file - --workers 1 --threads 8
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: GOOGLE_MAPS_API_KEY
        sync: false 